language: python
sudo: false
install:
  - pip install tox
cache:
  directories:
    - $HOME/.pip-cache
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  matrix:
    - TOXENV=py27-django16
    - TOXENV=py27-django17
    - TOXENV=py33-django16
    - TOXENV=py33-django17
    - TOXENV=py34-django16
    - TOXENV=py34-django17
    - TOXENV=pypy-django16
    - TOXENV=pypy-django17
before_script:
  - createdb django-pq
script:
  - tox
